name: "Slack Notification Action"
description: "Notificate the results of github actions for copebble projects"
inputs:
  webhook-url:
    description: "Slack Webhook URL"
    required: true
runs:
  using: "composite"
  steps:
    - name: Notification to Slack Channel
      uses: slackapi/slack-github-action@v2.1.1
      with:
        payload-file-path: "./payloads/${{ job.status }}-${{ github.event_name }}.json"
        payload-templated: true
        webhook: ${{ inputs.webhook-url }}
        webhook-type: incoming-webhook